
image: 
  - Visual Studio 2017
  - Visual Studio 2022

environment:
  matrix:
    - PATH: C:\Python37;%PATH%
      image_type: 2017
    - PATH: C:\Python37-x64;%PATH%
      image_type: 2017
    - PATH: C:\Python310;%PATH%
      image_type: 2022
    - PATH: C:\Python310-x64;%PATH%
      image_type: 2022

# Establish mapping between image_type env var and the visual studio version
# that should be used.
matrix:
  exclude:
    - image: Visual Studio 2017
      image_type: 2022
    - image: Visual Studio 2022
      image_type: 2017

build_script:
  - python setup.py build --clean

test_script:
  - python setup.py test
